### ISSUE TITLE
npm build - start fails 

### ISSUE THREAD

**Issue by idkjs** [troutowicz/bdc#1]
Just tried this and npm start keeps erroring out. Looks like its related to these similar issues as far as I can tell. Any idea? Thank you.

https://github.com/davezuko/react-redux-starter-kit/issues/350
https://github.com/developit/dropfox/issues/2

`Last login: Mon May 16 21:11:35 on ttys000
MacBook-Pro:bdc klik$ npm build
MacBook-Pro:bdc klik$ npm start

> bdc@0.1.0 start /Users/klik/projects/bdc
> babel-node --presets es2015 server.js

/Users/klik/.nvm/versions/node/v5.2.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413
          throw new Error( /_istanbul ignore next_/"Couldn't find preset " + /_istanbul ignore next_/(0, _stringify2.default)(val) + " relative to directory " + /_istanbul ignore next_/(0, _stringify2.default)(dirname));
          ^

Error: Couldn't find preset "es2015" relative to directory "/Users/klik"
    at /Users/klik/.nvm/versions/node/v5.2.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/klik/.nvm/versions/node/v5.2.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:405:20)
    at OptionManager.mergePresets (/Users/klik/.nvm/versions/node/v5.2.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:388:10)
    at OptionManager.mergeOptions (/Users/klik/.nvm/versions/node/v5.2.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:347:14)
    at OptionManager.addConfig (/Users/klik/.nvm/versions/node/v5.2.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:248:10)
    at OptionManager.findConfigs (/Users/klik/.nvm/versions/node/v5.2.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:454:16)
    at OptionManager.init (/Users/klik/.nvm/versions/node/v5.2.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:502:12)
    at compile (/Users/klik/.nvm/versions/node/v5.2.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:112:69)
    at loader (/Users/klik/.nvm/versions/node/v5.2.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:158:14)

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/klik/.nvm/versions/node/v5.2.0/bin/node" "/Users/klik/.nvm/versions/node/v5.2.0/bin/npm" "start"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! bdc@0.1.0 start: `babel-node --presets es2015 server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bdc@0.1.0 start script 'babel-node --presets es2015 server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bdc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --presets es2015 server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls bdc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/klik/projects/bdc/npm-debug.log
MacBook-Pro:bdc klik$ cd /Users/klik/.nvm/versions/node/v5.2.0/bin/
MacBook-Pro:bin klik$ ls
babel           jshint          webpack
babel-doctor        node            webpack-dev-server
babel-external-helpers  nodemon
babel-node      npm
MacBook-Pro:bin klik$ `

**Comment by troutowicz** [comment]
Hmm, I just built fine. I am on node v6.1.
